### ISSUE TITLE
Investigate RVD/ES failure for https

### ISSUE THREAD

**Issue by otsakir** [RestComm/RestComm-Core#725]
It seems that there are still some cases where accessing external services over https still fails. 

https://kcfe40tjod.execute-api.eu-west-1.amazonaws.com/

**Comment by otsakir** [comment]
Tried to reproduce locally on a /Mobicents-Restcomm-JBoss-AS7-7.5.0.757 instance without success.

**Comment by otsakir** [comment]
Copying the restcomm logs:

18:06:12,370 ERROR [org.mobicents.servlet.restcomm.rvd.http.resources.RvdController] (http-/172.17.0.27:443-2) Error processing ExternalService step step20: org.mobicents.servlet.restcomm.rvd.exceptions.ESRequestException: Error processing ExternalService step step20
	at org.mobicents.servlet.restcomm.rvd.model.steps.es.ExternalServiceStep.process(ExternalServiceStep.java:384) [classes:]
	at org.mobicents.servlet.restcomm.rvd.interpreter.Interpreter.interpret(Interpreter.java:345) [classes:]
	at org.mobicents.servlet.restcomm.rvd.model.steps.record.RecordStep.handleAction(RecordStep.java:126) [classes:]
	at org.mobicents.servlet.restcomm.rvd.interpreter.Interpreter.interpret(Interpreter.java:317) [classes:]
	at org.mobicents.servlet.restcomm.rvd.interpreter.Interpreter.interpret(Interpreter.java:277) [classes:]
	at org.mobicents.servlet.restcomm.rvd.http.resources.RvdController.runInterpreter(RvdController.java:89) [classes:]
	at org.mobicents.servlet.restcomm.rvd.http.resources.RvdController.controllerGet(RvdController.java:132) [classes:]
	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source) [:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_80]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) [jersey-server-1.13.jar:1.13]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) [jersey-server-1.13.jar:1.13]
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) [jersey-server-1.13.jar:1.13]
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) [jersey-server-1.13.jar:1.13]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [jersey-server-1.13.jar:1.13]
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) [jersey-server-1.13.jar:1.13]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [jersey-server-1.13.jar:1.13]
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) [jersey-server-1.13.jar:1.13]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1480) [jersey-server-1.13.jar:1.13]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1411) [jersey-server-1.13.jar:1.13]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1360) [jersey-server-1.13.jar:1.13]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1350) [jersey-server-1.13.jar:1.13]
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416) [jersey-servlet-1.13.jar:1.13]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538) [jersey-servlet-1.13.jar:1.13]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716) [jersey-servlet-1.13.jar:1.13]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.2.Final.jar:1.0.2.Final]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.2.0.Final.jar:7.2.0.Final]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_80]
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) [jsse.jar:1.7.0_80]
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154) [jsse.jar:1.7.0_80]
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1979) [jsse.jar:1.7.0_80]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1086) [jsse.jar:1.7.0_80]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332) [jsse.jar:1.7.0_80]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359) [jsse.jar:1.7.0_80]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343) [jsse.jar:1.7.0_80]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394) [httpclient-4.5.jar:4.5]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353) [httpclient-4.5.jar:4.5]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134) [httpclient-4.5.jar:4.5]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) [httpclient-4.5.jar:4.5]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) [httpclient-4.5.jar:4.5]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) [httpclient-4.5.jar:4.5]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) [httpclient-4.5.jar:4.5]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) [httpclient-4.5.jar:4.5]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) [httpclient-4.5.jar:4.5]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) [httpclient-4.5.jar:4.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) [httpclient-4.5.jar:4.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) [httpclient-4.5.jar:4.5]
	at org.mobicents.servlet.restcomm.rvd.model.steps.es.ExternalServiceStep.process(ExternalServiceStep.java:261) [classes:]
	... 38 more

**Comment by otsakir** [comment]
Looks like reproduction is possible on Restcomm-docker instance :-). Let's investigate...

**Comment by otsakir** [comment]
The issue is related to the SSL SNI extension. In the docker environment the extension is disabled in the JVM and that seems to cause the handshake_failure. I enabled it and the ES request worked just fine. 

Here is the offending flag from standalone.conf:
<code>-Djsse.enableSNIExtension=false</code>

Setting to true solved the issue.

SNI is to be an equivalent of Virtual Hosting but in HTTPS. It allows many different domains to be served over a single IP but in HTTPS (where at the time the SSL negotiation, the virtual host name is not yet available). 

There seems to be no solution to cover all cases out there. Some sites won't work with SNI support enabled and some others won't work without it. However, it's by default enabled on the JVM and the word out there is that only old sites that don't support this extension yet may cause trouble.

More info here:
https://en.wikipedia.org/wiki/Server_Name_Indication
http://forums.visokio.com/discussion/2614/security-server-ssl-error-handshake-alertunrecognized_name

@gvagenas, @deruelle

**Comment by deruelle** [comment]
@leftyb @gvagenas can you modify the standalone.conf as part of the restcomm build.xml release to include setting this flag to true ?

**Comment by leftyb** [comment]
sure @deruelle,

Will try to modify it when running the container. I will open a issue on that.
