### ISSUE TITLE
RestComm fails to cleanup bridge resources when timeout is received

### ISSUE THREAD

**Issue by hrosa** [RestComm/RestComm-Core#800]
When VoiceInterpreter receives a timeout while bridging process is in place, then it fails to do a proper cleanup of resources:

```
15:01:35,286 ERROR [org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter] (RestComm-akka.actor.default-dispatcher-95) java.lang.NullPointerException: org.mobicents.servlet.restcomm.fsm.TransitionFailedException: java.lang.NullPointerException
	at org.mobicents.servlet.restcomm.fsm.FiniteStateMachine.transition(FiniteStateMachine.java:89) [restcomm.commons-7.5.0.774.jar:]
	at org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter.onReceive(VoiceInterpreter.java:868) [restcomm.interpreter-7.5.0.774.jar:]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]
Caused by: java.lang.NullPointerException
	at org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter$FinishDialing.execute(VoiceInterpreter.java:1840) [restcomm.interpreter-7.5.0.774.jar:]
	at org.mobicents.servlet.restcomm.fsm.FiniteStateMachine.transition(FiniteStateMachine.java:87) [restcomm.commons-7.5.0.774.jar:]
	... 11 more
```

The problem is that at [this point](https://github.com/RestComm/RestComm-Core/blob/b050b26c869e8dd5948acc9a2d0d8c2db9f24b8d/restcomm/restcomm.interpreter/src/main/java/org/mobicents/servlet/restcomm/interpreter/VoiceInterpreter.java#L1834-L1834) the Interpreter is at bridging state and the dial branches have already been processed and set to null.

In this case, I advise to avoid trying to cancel dial branches and just process with proper call hangup and bridge cleanup.

**Comment by vfpuglia** [comment]
below is a link to the logs using the latest release (v7.5.030 + Jaime overlays). 

Let me know if you need anything else. 

https://www.dropbox.com/s/3dnel9w31l78it2/testing_2-2-2016.zip?dl=0

Thanks. 
Vince

**Comment by deruelle** [comment]
@vfpuglia Seems like an issue on Dialogic side on run 1 & 2:
https://gist.github.com/deruelle/1febe1400686d2e856d7 : ```Caused by: java.lang.ClassCastException: com.vendor.dialogic.javax.media.mscontrol.networkconnection.DlgcCreatedState cannot be cast to com.vendor.dialogic.javax.media.mscontrol.networkconnection.DlgcXSdpPortManagerStates```

@hrosa the Dialogic exception above on run2 end up leading to an Exception on RestComm side that we want to check https://gist.github.com/deruelle/5b6cfa9e6309ec6a813a

**Comment by hrosa** [comment]
Opened new issue related to failed call cleanup: https://github.com/RestComm/RestComm-Core/issues/848

**Comment by hrosa** [comment]
@deruelle @vfpuglia The open issue for the ClassCastException is https://github.com/RestComm/RestComm-Core/issues/803
