### ISSUE TITLE
Dialogic JSR309 driver has problems to create outbound call leg in Dial SIP scenarios

### ISSUE THREAD

**Issue by hrosa** [RestComm/RestComm-Core#802]
Every 3rd run I get the following issue. There are other ERROR lines which I think are associated with this one.
Note, I am running SIPp with 2 concurrent calls, 10 calls max, 2CPS.
 
```
20:09:29,499 ERROR [stderr - 71] (MSS-Executor-Thread-1) java.io.IOException: Operation not permitted
20:09:29,499 DEBUG [com.vendor.dialogic.javax.media.mscontrol.sip.DlgcSipB2BUA - 458] (MSS-Executor-Thread-0) APP-ID-0 - *** LEAVING SCHEDULETASK() **
20:09:29,499 DEBUG [com.vendor.dialogic.javax.media.mscontrol.networkconnection.DlgcXSdpPortManagerStates - 421] (MSS-Executor-Thread-0) Leaving Entering helperConnectLeg()
20:09:29,499 ERROR [stderr - 71] (MSS-Executor-Thread-1)          at java.net.PlainDatagramSocketImpl.send(Native Method)
20:09:29,500 DEBUG [com.vendor.dialogic.javax.media.mscontrol.fsm.DlgcFSM - 91] (MSS-Executor-Thread-0) Leaving Condition{ DlgcXSdpPortManagerFM: event[evProcessSdpOffer(SDP)] ==> NextState:DlgcXIvrLegPendState)}
20:09:29,500 DEBUG [com.vendor.dialogic.javax.media.mscontrol.networkconnection.DlgcNetworkConnectionProxy - 318] (MSS-Executor-Thread-0) Exiting SdpPortManagerProxy::processSdpOfferAsync Task run() => Media Server
20:09:29,500 ERROR [stderr - 71] (MSS-Executor-Thread-1)          at java.net.DatagramSocket.send(DatagramSocket.java:698)
20:09:29,501 ERROR [stderr - 71] (MSS-Executor-Thread-1)          at gov.nist.javax.sip.stack.UDPMessageChannel.sendMessage(UDPMessageChannel.java:835)
20:09:29,501 ERROR [stderr - 71] (MSS-Executor-Thread-1)          at gov.nist.javax.sip.stack.MessageChannel.sendMessage(MessageChannel.java:281)
20:09:29,502 ERROR [stderr - 71] (MSS-Executor-Thread-1)          at gov.nist.javax.sip.stack.SIPTransactionImpl.sendMessage(SIPTransactionImpl.java:892)
20:09:29,502 ERROR [stderr - 71] (MSS-Executor-Thread-1)          at gov.nist.javax.sip.stack.SIPClientTransactionImpl.sendMessage(SIPClientTransactionImpl.java:475)
20:09:29,503 ERROR [stderr - 71] (MSS-Executor-Thread-1)          at gov.nist.javax.sip.stack.SIPClientTransactionImpl.sendRequest(SIPClientTransactionImpl.java:1062)
20:09:29,503 INFO  [gov.nist.javax.sip.stack.UDPMessageChannel - 236] (Mobicents-SIP-Servlets-UDPMessageChannelThread-2) Setting SIPMessage peerPacketSource to: /146.152.122.168:5060
20:09:29,503 ERROR [stderr - 71] (MSS-Executor-Thread-1)          at org.mobicents.servlet.sip.message.SipServletRequestImpl.send(SipServletRequestImpl.java:1337)
20:09:29,504 ERROR [stderr - 71] (MSS-Executor-Thread-1)          at org.mobicents.servlet.sip.message.SipServletRequestImpl.send(SipServletRequestImpl.java:1009)
```

**Comment by hrosa** [comment]
related with https://github.com/RestComm/jain-sip/issues/53
