### ISSUE TITLE
Optimize MGCP usage on RestComm

### ISSUE THREAD

**Issue by hrosa** [RestComm/RestComm-Core#810]
RestComm should optimize MGCP usage by reducing the number of DLCX requests sent to the Media Server. This can be achieved by sending a DLCX straight at the endpoint (forcing it to clean all attached connections), instead of sending one DLCX per connection.

**Comment by hrosa** [comment]
Suggestion for new cleanup workflow for the MGCP Call Controller:

![endpoint-dlcx](https://cloud.githubusercontent.com/assets/7796608/12479419/d6542fda-c032-11e5-82e3-db3987a79621.png)

**Comment by hrosa** [comment]
Referencing commit: 627caafe4f89aa411e36768a7d7268458974f67c

MGCP Endpoint actors are now capable of sending DLCX requests through the Media Gateway. This forces MS to deletes the endpoint and all its connections.

The MmsCallController introduces a new Stopping state that asks the MediaGroup (IVR endpoint) and Bridge Endpoint to be closed. This will automatically delete the resources held bt Link and Connection actors, simplifying the cleanup process.

**Comment by hrosa** [comment]
Load tests done so far show stable CPU consumption during tests.
CPU consumption return to 1% when test finishes and scheduler threads are clean.

**Comment by hrosa** [comment]
An issue appeared when load testing hello-play with 400 concurrent calls and call rate of 100CPS

```
02:30:56,663 ERROR [org.mobicents.servlet.restcomm.telephony.Call] (RestComm-akka.actor.default-dispatcher-55) java.lang.ClassCastException: org.mobicents.servlet.restcomm.mscontrol.messages.MediaServerControllerStateChanged cannot be cast to org.mobicents.servlet.restcomm.telephony.CallFail: org.mobicents.servlet.restcomm.fsm.TransitionFailedException: java.lang.ClassCastException: org.mobicents.servlet.restcomm.mscontrol.messages.MediaServerControllerStateChanged cannot be cast to org.mobicents.servlet.restcomm.telephony.CallFail
	at org.mobicents.servlet.restcomm.fsm.FiniteStateMachine.transition(FiniteStateMachine.java:89) [restcomm.commons-7.5.0-SNAPSHOT.jar:]
	at org.mobicents.servlet.restcomm.telephony.Call.onMediaServerControllerStateChanged(Call.java:1559) [restcomm.telephony-7.5.0-SNAPSHOT.jar:]
	at org.mobicents.servlet.restcomm.telephony.Call.onReceive(Call.java:412) [restcomm.telephony-7.5.0-SNAPSHOT.jar:]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]
Caused by: java.lang.ClassCastException: org.mobicents.servlet.restcomm.mscontrol.messages.MediaServerControllerStateChanged cannot be cast to org.mobicents.servlet.restcomm.telephony.CallFail
	at org.mobicents.servlet.restcomm.telephony.Call$Failed.execute(Call.java:870) [restcomm.telephony-7.5.0-SNAPSHOT.jar:]
	at org.mobicents.servlet.restcomm.fsm.FiniteStateMachine.transition(FiniteStateMachine.java:87) [restcomm.commons-7.5.0-SNAPSHOT.jar:]
	... 12 more
```

**Comment by hrosa** [comment]
ClassCastException fixed by 0e848de9153dbe09b594011d60bf9d9b3fadaf0a

**Comment by hrosa** [comment]
Manual tests show that Media Resources are properly cleaned for conference calls.

**Comment by hrosa** [comment]
Started load testing. Resource cleanup seems fine.

Special case: RestComm starts rejecting calls when participants number exceeds (40). Cleanup is executed flawlessly.

**Comment by hrosa** [comment]
Load testing Dial SIP scenario showed some errors on Sip Servlets side, as described here https://github.com/RestComm/sip-servlets/issues/107

**Comment by hrosa** [comment]
Dial SIP load test with 300 concurrent calls and call rate of 10 CPS. 1 failed call out of 10k total calls.
Media Server cleanup is performed flawlessly:

![screen shot 2016-01-26 at 17 13 17](https://cloud.githubusercontent.com/assets/7796608/12612078/37f723f0-c4e8-11e5-894a-a14f3be93fee.png)

NOTE: MGCP timeout interval had to be increased from 500ms to 1500ms to avoid timeouts.

**Comment by hrosa** [comment]
Tested hello-play scenario with announcement looping for over 1 minute.
Was able to achieved 1000 concurrent calls with call rate of 100 CPS. Test ran for almost 2h and performed 80k calls in total.
Cleanup is working flawlessly on Media Server side, with CPU consumption dropping down to 1% after test completion.
The [RestComm log](https://github.com/RestComm/RestComm-Core/files/109667/restcomm-log.txt) shows very few errors, while Media Server log is clean.

![screen shot 2016-01-29 at 02 10 01](https://cloud.githubusercontent.com/assets/7796608/12674860/1e348e16-c67e-11e5-8834-744c865f6ef5.png)

**Comment by hrosa** [comment]
Tried repeating the test with 1-minute wav files instead of looping the same announcement over and over again.

There were some issues, with the test freezing suddenly and SIPp, Profiler, RestComm and Media Server becoming unresponsive for about a minute. The problem is related with IO problems probably either at OS level or in the Media Server audio player implementation.

The following exception seems to be the main sympton

```
17:26:04,254 ERROR [RtpTransmitter] No buffer space available
java.io.IOException: No buffer space available
    at sun.nio.ch.DatagramDispatcher.write0(Native Method)
    at sun.nio.ch.DatagramDispatcher.write(DatagramDispatcher.java:51)
    at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
    at sun.nio.ch.IOUtil.write(IOUtil.java:51)
    at sun.nio.ch.DatagramChannelImpl.write(DatagramChannelImpl.java:616)
    at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:462)
    at org.mobicents.media.server.impl.rtp.RtpTransmitter.send(RtpTransmitter.java:170)
    at org.mobicents.media.server.impl.rtp.RtpTransmitter.send(RtpTransmitter.java:248)
    at org.mobicents.media.server.impl.rtp.RTPOutput.onMediaTransfer(RTPOutput.java:140)
    at org.mobicents.media.server.impl.AbstractSink.perform(AbstractSink.java:165)
    at org.mobicents.media.server.impl.AbstractSource$Worker.perform(AbstractSource.java:431)
    at org.mobicents.media.server.scheduler.Task.run(Task.java:122)
    at org.mobicents.media.server.scheduler.PriorityQueueScheduler$WorkerThread.run(PriorityQueueScheduler.java:424)

[5:31] 
and following this message

[5:31] 
17:26:08,020 ERROR [WavTrackImpl] java.net.SocketException: Connection reset
```

This can be an OS limitation, as explained [here](http://stackoverflow.com/questions/1043567/java-ioexception-no-buffer-space-available-while-sending-udp-packets-on-linux). Still, the implementation of the audio player should be reviewed nonetheless because shorter announcements are playing fine (even at higher loads, like1000 concurrent calls). Related issue is https://github.com/RestComm/mediaserver/issues/45

**Comment by hrosa** [comment]
Tested a Conference call scenario, with a conference room being created for each call.
Tested a total of 30k calls, with 1k concurrent calls and a call rate of 100CPS. CPU consumption was 40-50% and cleanup is working flawlessly.

![screen shot 2016-01-29 at 15 50 16](https://cloud.githubusercontent.com/assets/7796608/12680117/069767ca-c6a0-11e5-8818-8e6a1c46f696.png)

**Comment by gvagenas** [comment]
Pull request reviewed and merged to master https://github.com/RestComm/RestComm-Core/pull/840
