### ISSUE TITLE
NPE on FinishingDialing state

### ISSUE THREAD

**Issue by jaimecasero** [RestComm/RestComm-Core#835]
This is part of XMS Dialogic integration activity:

logs:
10:57:40,335 INFO  [org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter - 72] (RestComm-akka.actor.default-dispatcher-3)  ********** VoiceInterpreter's akka://RestComm/user/$V Current State: bridging
10:57:40,335 INFO  [org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter - 72] (RestComm-akka.actor.default-dispatcher-3)  ********** VoiceInterpreter's akka://RestComm/user/$V Processing Message: akka.actor.ReceiveTimeout$
10:57:40,336 INFO  [org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter - 72] (RestComm-akka.actor.default-dispatcher-3) FinishDialing, current state: bridging
10:57:40,336 INFO  [org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter - 72] (RestComm-akka.actor.default-dispatcher-3) Received timeout, will cancel branches, current VoiceIntepreter state: bridging
10:57:40,338 ERROR [org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter - 64] (RestComm-akka.actor.default-dispatcher-3) java.lang.NullPointerException: org.mobicents.servlet.restcomm.fsm.TransitionFailedException: java.lang.NullPointerException
	at org.mobicents.servlet.restcomm.fsm.FiniteStateMachine.transition(FiniteStateMachine.java:89) [restcomm.commons-7.5.0.24.jar:]
	at org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter.onReceive(VoiceInterpreter.java:882) [restcomm.interpreter-7.5.0.24.jar:]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]
Caused by: java.lang.NullPointerException
	at org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter$FinishDialing.execute(VoiceInterpreter.java:1822) [restcomm.interpreter-7.5.0.24.jar:]
	at org.mobicents.servlet.restcomm.fsm.FiniteStateMachine.transition(FiniteStateMachine.java:87) [restcomm.commons-7.5.0.24.jar:]
	... 11 more

**Comment by jaimecasero** [comment]
duplicate of https://github.com/RestComm/RestComm-Core/issues/800
