### ISSUE TITLE
RVD Diagram fails to display properly on Chrome

### ISSUE THREAD

**Issue by otsakir** [RestComm/RestComm-Core#872]
New RVD diagram functionality fails on Chrome (version 48 was tested but probably other versions fail too). Firefox works ok.

Only the root node is displayed and the following exception is thrown in the logs:

```
GET http://192.168.1.39:8080/restcomm-rvd/services/projects/test/settings 404 (Not Found)(anonymous function) @ angular.min.js:93p @ angular.min.js:89g @ angular.min.js:86(anonymous function) @ angular.min.js:119n.$eval @ angular.min.js:133n.$digest @ angular.min.js:130n.$apply @ angular.min.js:133h @ angular.min.js:87K @ angular.min.js:91z.onload @ angular.min.js:93
angular.min.js:107 TypeError: this.node.getTransformToElement is not a function
    at Object.VElement.bbox (http://192.168.1.39:8080/restcomm-rvd/js/lib/joint.js:17130:36)
    at joint.dia.ElementView.joint.dia.CellView.extend.positionRelative (http://192.168.1.39:8080/restcomm-rvd/js/lib/joint.js:21041:51)
    at null.<anonymous> (http://192.168.1.39:8080/restcomm-rvd/js/lib/joint.js:21011:18)
    at http://192.168.1.39:8080/restcomm-rvd/js/lib/joint.js:9682:23
    at Function.forEach (http://192.168.1.39:8080/restcomm-rvd/js/lib/joint.js:11876:15)
    at joint.dia.ElementView.joint.dia.CellView.extend.update (http://192.168.1.39:8080/restcomm-rvd/js/lib/joint.js:21001:11)
    at bound [as update] (http://192.168.1.39:8080/restcomm-rvd/js/lib/joint.js:10155:23)
    at joint.dia.ElementView.joint.dia.CellView.extend.render (http://192.168.1.39:8080/restcomm-rvd/js/lib/joint.js:21204:14)
    at joint.dia.Paper.Backbone.View.extend.addCell (http://192.168.1.39:8080/restcomm-rvd/js/lib/joint.js:23305:14)
    at bound (http://192.168.1.39:8080/restcomm-rvd/js/lib/joint.js:10155:23) <div class="text-center" id="paper" style="overflow: scroll;" ng-init="drawGraph()">
```

**Comment by otsakir** [comment]
Tried to upgrade joint.js graphhics library to latest version (0.9.6) without success. It broke firefox too.

**Comment by otsakir** [comment]
Seems there is indeed an issue with JointJS and chrome 48. See more here:

https://groups.google.com/forum/#!topic/jointjs/qIKIiJCEClI
